//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfaceEstoque
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingrediente
    {
        public int id_ingrediente { get; set; }
        public string nome { get; set; }
        public Nullable<int> quant_atual { get; set; }
        public Nullable<int> quant_max { get; set; }
    }
}
